version: '2'

services:
    postgres:
        image: postgres:11.5
        ports:
            - "5760:5432"
        restart: always
        volumes:
            - $PWD/tests/database/dump:/docker-entrypoint-initdb.d/
        environment:
            - "POSTGRES_DB=projeto"
            - "POSTGRES_USER=projeto"
            - "POSTGRES_PASSWORD=mysecretpassword"

    api-test:
        image: arquiteturansj/flask:2.2
        restart: always
        ports:
            - "80:80"
            - "5678:5678"
        volumes:
            - $PWD:/var/www/html
            - $PWD/logs:/var/log/nasajon
            - $PWD/wsgi_dev.ini:/etc/wsgi/wsgi.ini
        env_file:
            - .env.dist
        command: sh -c "python3 -m pip install -r /var/www/html/requirements.txt --no-cache-dir && /entrypoint.sh"
        depends_on:
            - postgres

    test:
        image: arquiteturansj/flask:2.2
        volumes:
            - $PWD:/var/www/html
            - $PWD/logs:/var/log/nasajon
        env_file:
            - .env.dist
        command: sh -c "python3 -m pip install -r /var/www/html/requirements.txt --no-cache-dir && python3 -m pip install -r /var/www/html/requirements-dev.txt --no-cache-dir && pytest -s tests/api/casos_de_teste"
        depends_on:
            - postgres
            - api-test

    redis:
        image: redis:7-alpine
        container_name: redis-stream-test
        ports:
            - "6379:6379"

    redisinsight:
        image: redis/redisinsight:latest
        container_name: redisinsight
        ports:
            - "5540:5540"
        depends_on:
            - redis
